binding_name: gptq
ctx_size: 2048
active_personality_id: 0
host: localhost
model_name: starcoderplus-GPTQ
n_predict: 1024
n_threads: 8
override_personality_model_parameters: false
personalities:
- english/generic/lollms
port: 9600
repeat_last_n: 40
repeat_penalty: 1.2
seed: -1
temperature: 0.9
top_k: 50
top_p: 0.95
user_name: user
version: 5
